modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

# Optional integrations — soft deps
[[dependencies.${mod_id}]]
    modId="kubejs"
    mandatory=false
    versionRange="[2001.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="irons_spellbooks"
    mandatory=false
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="epicfight"
    mandatory=false
    versionRange="[20.14,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="apotheosis"
    mandatory=false
    versionRange="[7.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="l2hostility"
    mandatory=false
    versionRange="*"
    ordering="NONE"
    side="BOTH"
